#!/bin/sh

if command -v pactl &>/dev/null; then
    pactl get-sink-volume $(pactl get-default-sink) | awk -F '[^0-9]+' '/left:/{print $3}'
elif command -v wpctl &>/dev/null; then
    wpctl get-volume @DEFAULT_SINK@ | awk -F' ' '/Volume:/{print $2}'
else
    amixer -D pulse sget Master | awk -F '[^0-9]+' '/Left:/{print $3}'
fi
